---

- name: mysql80 mgr install
  hosts: server
  become: yes
  gather_facts: yes
  roles:
    - mysql80_install
  tags: mysql80install

- name: zabbix install
  hosts: server
  gather_facts: no
  become: yes
  roles:
    - zabbix_install
  tags: zabbixinstall

- name: mgrcheckclient install
  hosts: server
  gather_facts: no
  become: yes
  roles:
    - mgrcheckclient_install
  tags: mgrcheckclientinstall

