---

- name: mysql57 mgr install
  hosts: server
  become: yes
  gather_facts: yes
  roles:
    - mysql57_install

- name: zabbix install
  hosts: server
  gather_facts: no
  become: yes
  roles:
    - zabbix_install
  tags: zabbixinstall
