---

- name: mysql56 mgr install
  hosts: server
  become: yes
  gather_facts: yes
  roles:
    - mysql56_install
  tags: mysql56install

- name: zabbix install
  hosts: server
  gather_facts: no
  become: yes
  roles:
    - zabbix_install
  tags: zabbixinstall
