---

#软连接路径
mysql_base_dir: "/usr/local/mysql56"
##安装包文件名，必须先在下载安装包到./roles/download/目录
mysql_install_file: "Percona-Server-5.6.24-rel72.2-Linux.x86_64.ssl101"

primary_host: "{{ groups['server'][0] }}"
mgr_Listen_Port: "{{ mysql_port | int + 20000 }}"
mysql_mgr_host: "{{ groups['server'] }}"

#primary_host: "{{ groups[mgr_group][0] }}"
#mysql_mgr_host: "{{ groups[mgr_group][0:10] }}"