---

- name: yum install MySQL-python
  yum: name=MySQL-python state=latest

- name: copy start sql file
  template: src='{{ item }}.sql.j2' dest='/usr/local/src/{{item}}.sql'
  with_items:
    - start_replication
  tags: copystartsqlfile

- name: start mgr primary
  shell: /{{ mysql_base_dir }}/bin/mysql --socket={{ data_dir }}/mysql.sock < /usr/local/src/{{ item }}.sql
  tags: startmgrprimary
  with_items:
    - start_replication
  when: ansible_default_ipv4.address == primary_host

- name: start mgr slave
  shell: /{{ mysql_base_dir }}/bin/mysql --socket={{ data_dir }}/mysql.sock < /usr/local/src/{{ item }}.sql
  tags: startmgrslave
  with_items:
    - start_replication
  when: ansible_default_ipv4.address != primary_host

- name: copy default_mysql_user mgr_member_status file
  copy: src='{{ item }}.sql' dest='/usr/local/src/{{ item }}.sql'
  with_items:
    - default_mysql_user
    - mgr_member_status
  tags: copydefaultfile

- name: test my_rep login
  shell: /{{ mysql_base_dir }}/bin/mysql -h {{ ansible_default_ipv4.address }} -P {{ mysql_port }} -u{{ mysqlrep_name }} -p{{ mysqlrep_pwd }} -e "select 1"
  tags: testmyreplogin


- name: create default_user mgr_member_status
  shell: /{{ mysql_base_dir }}/bin/mysql --socket={{ data_dir }}/mysql.sock -u{{ mysqlroot_name }} -p{{ mysqlroot_pwd }} < /usr/local/src/{{ item }}.sql
  tags: createdefaultsql
  with_items:
    - default_mysql_user
    - mgr_member_status
  when: ansible_default_ipv4.address == primary_host
