---

##修改主机名
- name: get host name
  shell: hostname
  register: old_hostname_status
  tags: changehostname

- name: debug hostname
  debug: msg="hostname:{{ old_hostname_status.stdout }}"
  tags: changehostname

- name: change hostname
  hostname: name="{{ hostname }}"
  when: old_hostname_status.stdout != hostname
  tags: changehostname
  ignore_errors: True

- name: exit task if port has bin userd
  fail: msg="system is not centos 6"
  when: ansible_distribution != "CentOS" and ansible_distribution_major_version != "6"

- name: yum install
  shell: yum install -y lrzsz perl perl-DBI perl-DBD-MySQL libev perl-Time-HiRes perl-IO-Socket-SSL python MySQL-python sysstat xfsprogs lzop socat openssl-devel libselinux-python libaio-devel gdb perl-TermReadKey
  tags: yuminstall

- name: yum rpm install
  yum: name={{ item }} state=present
  with_items:
  - "http://10.201.3.50/software/MegaCli-8.07.07-1.noarch.rpm"
  - "http://10.201.3.50/software/percona-xtrabackup-24-2.4.9-1.el6.x86_64.rpm"
  - "http://10.201.3.50/software/percona-toolkit-3.0.5-1.el6.x86_64.rpm"
  - "http://10.201.3.50/software/pigz-2.3.3-1.el6.x86_64.rpm"
  - "http://10.201.3.50/software/mha4mysql-node-0.56-0.el6.noarch.rpm"
  ignore_errors: True
  tags: yumrpminstall

- name: get kernel parameter
  shell: cat /boot/grub/grub.conf |grep deadline |wc -l
  register: get_kernel_status
  tags: changekernel

- name: change centos6 kernel parameter
  shell: sed "s/rd_NO_DM rhgb quiet/rd_NO_DM rhgb quiet  elevator=deadline/g" -i /boot/grub/grub.conf
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6" and get_kernel_status.stdout|int == 0
  tags: changekernel

- name: change centos7 kernel parameter
  replace: dest=/boot/grub/grub.conf regexp="LANG=en_US.UTF-8" replace="LANG=en_US.UTF-8 elevator=deadline"
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7" and get_kernel_status.stdout|int == 0
  tags: changekernel

- name: change io scheduler
  shell: "{{ item }}"
  with_items:
  - "echo deadline > /sys/block/sda/queue/scheduler"
  - "echo deadline > /sys/block/sdb/queue/scheduler"
  ignore_errors: True
  tags: changeioscheduler

- name: change sysctl
  sysctl: name="vm.swappiness" value=5 sysctl_set=yes state=present reload=yes
  tags: changeioscheduler

- name: change sysctl
  sysctl: name="fs.aio-max-nr" value=262144 sysctl_set=yes state=present reload=yes
  tags: changeioscheduler

- name: change centos6 nproc conf
  shell: "{{ item }}"
  with_items:
  - "sed -i '/nproc/s/soft/-/' /etc/security/limits.d/90-nproc.conf"
  - "sed -i '/nproc/s/1024/65535/' /etc/security/limits.d/90-nproc.conf"
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"
  tags: changenprocconf

#- name: change centos7 nr_open conf
#  sysctl: name="fs.nr_open" value=10240000 sysctl_set=yes state=present reload=yes
#  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
#  tags: changenprocconf

- name: change centos7 nproc conf
  lineinfile: dest=/etc/security/limits.d/20-nproc.conf regexp="4096" line="*          soft    nproc     65536"
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
  tags: changenprocconf

- name: change centos7 nproc conf
  shell: "su mysql -c 'ulimit -u 65535'"
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
  tags: changenprocconf

- name: debug parameter
  debug: msg="system version:{{ ansible_distribution }} {{ ansible_distribution_version }} {{ get_kernel_status.stdout}}"
  tags: changehostname

